export async function load({ params }) {

	let text = `day,main,domain,start,end,comment,resources,breakpoints
11/5/2024,"Landing, Nav Bar",Design,7h,19h,Criando a Landing Page,0,0
11/8/2024,"Feedback, Statistics Question Modules",Design,17h,22h,Testando os módulos de feedback,0,0
11/11/2024,"Question Side Bar, Question Social Panel, Question Content Panel",Design,7h,19h,Brainstorming Panels Structure,0,0
11/12/2024,"Question Tool Bar, Question Social Panel Comments, Question Content Panel Body, Question Content Panel Full Answer, Question Content Panel Footer",Design,7h,19h,Finishing things due yesterday,0,0
11/13/2024,"OAuth, API, API Keys, Self-hosting",Research,7h,19h,Studying how the oAuth Protocol works whilst figurinh out how to make a public api that has metrics and permissions. Also checking self hosting solutions,0,0
11/14/2024,"Designing Grammar for the Editor, Abstract Syntax Tree, Syntax Tree",Research,9h,19h,"Figuring out how am I going to store the editor document in a database, whats the best format (should I use plain HTML, XML, JSON) and whats the best and consolidated structure of doing so (Google Docs approach seems perfect for my case)",How Discord Renders Rich Messages on the Android App,0
11/15/2024,"Google OAuth2.0 Protocol Authentication, Grammar for the editor, Reading OAuth2.0 Protocol, Hashing",Research,7h,22h,Studying the oAuth2.0 standard by implementing Google APIS authentication. Reading the whole standard to get a full grasp of it. Researching which access token should use (JWT). Figuring out a way to safely store them in the database base in order to prevent attacks. Researching criptography implamentations.,https://medium.com/leonard-cyber/how-really-to-store-your-users-passwords-and-api-tokens-which-are-passwords-5132cec8835b;  https://crackstation.net/hashing-security.htm; https://developers.google.com/identity/protocols/oauth2/web-server#httprest; https://developers.google.com/identity/protocols/oauth2/web-server; https://medium.com/google-cloud/understanding-oauth2-and-building-a-basic-authorization-server-of-your-own-a-beginners-guide-cf7451a16f66; https://github.com/bitwiseshiftleft/sjcl?tab=readme-ov-file; https://datatracker.ietf.org/doc/html/rfc6749#section-3.1,0
11/16/2024," Fine Grained Block Permissions, User Roles, Document Permission",Code,7h,19h,"Iterating over different approaches for block editor with fine grained block permission scopes such as view, edit, share, react and so on. Also, trying to stablish a model for user roles and in-document permissions. Failed miserably and delegated task to the next day.",0,0
11/17/2024,Strongly Typed Event Driven Structured Node Tree with Middlewares,Code,7h,9h,"Finally settling for a strongly typed event driven node tree with middlewares. Similar to how a HTML would work in the sense that events bubble up, but block internal operations such as adding a child or moving it up in a array also triggers events. This will allow for example, a observer to respond to any changes in a nested child so we can change properties like last updated by for individual nodes that propagate up to the document. However, I still haven't solved the problem of fine grained permissions for individual blocks, which I think will be feasible once the data structure is implemented.",0,0
11/17/2024,"Schema, ReordableArray",Code,21h40,23h40,"Implementing the Rigid in a sense that every class has to follow a pre-defined schema that throws if it doesn't. Also, creating an Array that can swap elements within.",0,0
11/18/2024,"Center Panel, Left Panel, Right Panel, Navigation Bar, Sketch, Manifesto",Design,7h,21h30,Writing the project manifesto and redisgning the UI to comply with Functionalities 2.3,0,0
11/19/2024,Left panel,Design,7h,9h30,Creating a better navigation system for UI left panel based of figma-s comment section,0,0
11/19/2024,Project Scope,Research,10h,14h30,Defining project scrope and elaborating action plan,0,0
11/20/2024,"Schema, Proxy",Code,7h,20h30,"Coding the main type structure of the STED STN. I took a different approach for the previous implementation. It kinda looks like an interface so I wonder if it would be less painful to just learn typescript or jsdoc once and for all. Nonethless, everything seems to be working just fine. Now, the only caveat is the separtion of concerns of the functions that is really mind bogling me. Also, took a look in the Proxy API documentation, I wasn't aware it existed",0,breakpoint
11/21/2024,schema,Code,8h,18h15,"Basically a back and forth non-stop with this class that has plagued my whole existence. It is so damn annoying getting it to work, but at last nonetheless I think I found out what was making it work unexpectedly. Basically, I was trying to hand down state instead of returning it and assigning in the variable (in a recursion to even make me look more fool). However, I didn't not figure it out yet and dispite having worked for about 30 hours only in this function, it is far from being either optimazed nor maintainable long term. The next step will be to refactor each and every single one of its components into folders as I understimated how a pain in the ass would a thousand lines file be. Failed miserably  delegating this task for 2 days into the future.",0,0
11/21/2024,schema,Code,20h,22h30,"Prototyping refactoring of the class. Went suprisingly well and one of the thousands of bad logic was actually unecessary overhead because the function was not really recursive in objects, because it would left out arrays for a separate handler.",0,0
11/22/2024,assert-is,Code,5h30,6h50,"Developing my own library of asserts and tests, because I got tired of writing exceptions. ",0,0
11/22/2024,"Comment, Comment Actions Popover, Comment Visibility Popover, Comment Remaining Popover, Formulas, Formula User Popover, Formula User Popover AddFriend, Formula Book Popover; Visual Hierarchy",Design,7h30,17h,"Had a lot of different ideas, most of them were already planned, but some rolled in along the way, one of them being science and engineering celebrities across time having special profiles that will be just like normal users, controlled programatically through the API or through an UI by an administrator, that sends messages in special times in the forums. Got some laughs with Newton and Einstein. Unfortunately, I tried buying the domain today, but, as a minor, I cannot. Fine, I will just wait a full month before even creating a git repository. That said, there isn't much I can do regarding the implementation of oAuth untill I get the server to mess with the http headers.",https://dribbble.come,0
11/23/2024,"Product Popover Testimonial, Removing Product Popover testimonial",Design,6h30,9h30,"Spent some time tweakling the interface, because something just wasn't right about the way the product preview poped up. I ended up designing a testimonial, but later asked myself: why the heck a product testimonial in a product preview, as it is meant to be literally a preview not a whole view? So I ended up removing it later.",0,0
11/23/2024,Input Styling,Research,9h30,10h45,"After I finished the product popover, I went on designing the formulas extensible panel. Turns out it would be waaay harder than I firstly thought. So, I researched a lot about input styling and in the mid time, this reasearch elucidated some aspects that made the UI look clunky and figured it was the lack of room to breath. Then, I created another page, took some inspiration from some crypto websites and got to work. Now, I am a little bit happier with the result, though it means I will have to redesign everything I did yesterday. However, as it became more consistent - because now I am using something called a design system - I reckon it will be faster and won't take so long, judging half a period later I did twice as much work than yesterday. ",https://www.setproduct.com/blog/input-ui-design;https://dribbble.com/shots/23471891-Fullmoon-Cryptocurrency-Dashboard;https://dribbble.com/shots/19614098-E-Commerce-website-e-commerce-Product-Page ,0
11/23/2024,Formula,Design,11h30,14h15,Redesigning the right side bar because I was literally felling claustrophobic.,0,0
11/23/2024,Formula,Design,16h30,19h44,"Fucking awesome. I took a different approach. The right side bar was genuiely so clustered I caught myself holding my breath a few times. Now it has much mroe padding, a lightweight look and room, plus, by doing this way, I some aspects of the UI that were still cloudy in my mind regarding implementation suddenly came to life. ",0,0
11/23/2024,Formula,Design,21h15,22h41,Finishing 3/4 of the details. Somehow I just cant fit the book  within a space the doesn't it make look rushed,0,0
11/24/2024,Schema,Code ,5h30,14h30,Once more working on the literal backbone of everything,0,0
11/24/2024,Schema,Code,15h40,19h20,"Holy shit, I didn't even know you could acess the constructor from any arbirtary thing. I was reading about Remote Code Execution, as users will be able to create their own documents and the properties they send will have to be validated before acessed, when I saw a snippet from eslint node security that showed me something really weird. At first, I thought it was something from previous implementations, but, as it turns out, it is so insecure that my own eslint doesn't even show it and, therefore, I had no ideia it even existed. Thats why this means that everything has to be structured and strongly typed as I said in earlier comments. But regarding the schema, I am actually unsure if the use of proxies would be advisible, although they essentialy obly me to use another object and not a constructor, undermining my backend developer qualitiy of life and taking a toll on readability. However, I can similate the proxies by using Object.seal() and defining the getters and setters I want to be used. I think this will allow for more flexibility and a long term intuitive approach. When someone comes to develop with me, they will be used to the inheritance syntax and won't acutally worry about the schema implementation. ",0,0
11/25/2024,Schema,Code,5h20,9h30,"Well, after some ground breaking exploration regarding proxies I settled for them and to be honest it was the best decision I have ever made. They are so flexible to work with and not only provide a true proximity with the native methods, but they also allow seamlessly error handling right out of the box without any modification of the logic. This has literally just expaanded the boundaries of what I thought I had known previously regarding these methods. However, one of the problems I still have is that I had to compromise modifiers, though in my honest opinion they were not a good ideia anyways. So, that said, the not extensibility of the array is going to be delegated to an abstraction that will sit on top of the schema class",0,0
11/25/2024,Schema,Code,12h20,17h30,"Literally, almost finished. There are some minor minor details that have to be implemented in order for everything to be working. I reckon a dozen more hours and it will be error proof and well tested enough so that I can move on.",0,0
11/25/2024,Schema,Code ,18h,20h04,"FUCKING AMAZING I FUCKING DID IT. I actually had forgotten the feeling of getting something to work after about what? 60 hours or so. It is working wonders and one of the main things that literally made me smile non-stop is that what I had been designing is so good, that errors that otherwise would have been a pain in the ass to find, now literally just pop up in a very descriptive manner. Comparing to what I had just a few days ago, where I couldn't have access to the call stack because everything was thrown and caught without regard for the line where it happened, I really almost cried of seeing everything working beautifully. Now, I have to code a few dozen tests for class to ensure I will not break it, and, afterwards, I will be able to create the Block abstraction for the editor. To be honest, I am so tired that I didn't even test each edge case. So I am saying it is working, though I am not so sure because I just closed vs code and will only think about it again in 2 days.",0,0
11/26/2024,Formula,Design,6h30,12h,Integrated most part of the formula funcionality although right now I am trying to figure out a way to put the conversor without too much screen polution,0,0
11/26/2024,"Firebase, Hosting Providers",Research,14h00,18h20,"Fucking frustated. Most of the websites that are out there essentialy charge about $25 for a mid-sized instance with little or no provisions. As this app is meant to have complex behavior, I think I will not be able to escape from literally buying a VPS when I want to develop in production. Thank got ssl certificates are free and will allow me to host this thing on my computers anyways. The only problem is going to be cache, as I will probably have to pay for a CDN anyways.",0,0
11/26/2024,"Static IP, Containerization, Claro FIBRA para empresas, Nginx",Research,18h20,19h20,"I am a fucking genius. Basically I went from having to spent a lot, with very limitied resource to have to spend what I will already spend whilst having virutally unlimited resources. Sometimes I wonder how smart one has to be to beat my clever solutions to totally unrelated problems.",0,0
11/27/2024,"Formula Third Variable, Formula Recent Search, Formula Autocomplete, Feature Review Manifesto, Frequência, Feature Review - Drawer de Fórmulas",Design,7h,19h,"Writing feature review workflow, writing frequency of features sent to review, finishing and polishing the Formula design. ",0,0
11/28/2024,Nosso Estudo Reports,Code,9h30,21h,"Building a simple website tthat displays this exact table, but in a more user friendly way. ",0,0
11/29/2024,Nosso Estudo Reports Github Pages Deployment,Code,6h30,9h30,"Figuring out the things I have to do in order to make the website, which is dinamic, become static. I ended up using a pretty lazy approach, as I am not willing, nor it is the right time to deal with the inner workings of vite an svelte. At any rate, the website is deployed live on my github.",0,0
11/29/2024,Indexing Learning Resources,Research,9h30,14h00,"As I did with my last project, in order to keep things scoped and time constraints manageable, I have to index every single one of the learning resources of the techonologies I will essentialy have to learn from scratch. This process takes about a day, but I managed to do a lot of it already. I have created a fig jam file that described the stack and the general order I will have to learn them, altogether with a spreadsheet that by now has 1600 lines of website headers, subheaders and links to pages.",0,0
11/29/2024,Indexing Learning Resources,Research,16h30,19h40,"Holy shit, I have so much to learn that I doubt I will be able to pull this off in less than three months. Honestly, after indexing everything, things look much bigger than I first thought, so I might have to reschedule updates on design in order to account for that. Actually, I think this is pretty much what I am gonna do. I will take the approach I took in the past that is one topic per day alternating in order, non stop. The only problem is exercises. I will adress those later when I finish indexing WSL, Docker Engine, Docker Build and Docker Compose.",0,0
11/29/2024,"Indexing Learning Resources, Design Inspirations",Research,20h40,23h30,"One of the bottlenecks for what I am developing in my outrageous inability to design things that look great. Don't get me wrong, I know this is a matter of not having enough training data in my mind as I have never got much deeper into the design world, but I will have to find a way to do so and just today I browsed a few websites that looked really cool. Additionally, they have a lot of small coding and designing challeges that I found amazing and they actually were a lot harder than what I first thought. However, my main struggle is with creativity and drawing. I don't fucking know how to draw and I can't seem to find a good resource in order to learn doing so. I have an ideia of how am I going to get better, but for this I will have to spendd a little more money than what I am comfortable with. Not now thought: I have an indexed spreadsheet of all the documentations of the tech stack I will need and they are HUGE.",0,0
11/30/2024,WSL,Research,7h20,11h40,"Reading and figuring out how to set up the WSL on my windows machine, as I plan to use it for double purposes: As a server and a workbench. To be honest, I am loving this approach, because it gives me an excuse to learn things I have always wanted to learn anyways. Reading WSL Manual 0-101/315",0,0
11/30/2024,"WSL, Linux chmod Command",Research,13h14,18h20,"Learning about the configuration files on each of the host machines, that is, windows and wsl through the .wslconfig and wsl.conf respectively",0,0
12/1/2024,"Linux Basic Commands, Installing Docker, Docker Breaking Down Instalation Script Line-by-Line, Linux Creating Users, Linux Modifying Users, Linux Deleting Users, Docker Running Containers as Non Root, Linux grep Command, Linux cat command, Linux tee command, Linux install command, Linux awk package, Docker Storage ",Research,12h30,17h30,"Alright, messed around with a few of linux's commands and actually was able to do some basic stuff such as creating and removing users, running docker as non root users to avoid security reasons (not sure about that still, I will finish reading the documentation in order to give my verdict) and, now, I will pause for a bit, buy things that are running low here and after that, start indexing the elastic search for the search engine (Although by the looks of it, I will have to do this more frequently than not, because with the ever increasing stack I am building and pllaning to use, this will grow and grow non-stop). Somehow, I was so settled for the amount of time I will have to invest that having to increase even more just caused a little panic in my mind. Nothing unmanageable though. ",0,0
12/1/2024,Indexing Learning Resources,Research,18h20,20h00,"Fucking hell, the index I did yesterday is alread outdated because a fucking library updated just dropped yesterday. What a shit show. AW FUCK I AM SO FUCKING ANGRY. LITERALLY HALF OF THE FUCKING INDEX IS JUST FILLED WITH FUCKING ELASTIC SEARCH. THERE ARE JUST SO MANY ARTICLES.",0,0
12/1/2024,Web Scrapping,Code,20h00,23h00,"I wasn't gonna do it, but I need to know how much time to allocate given it's a limited resource. And now I have over 3000 links indexed with all their text saved. I was going to save their html though, but I figured that wouldn't be necessary. I set up 4 parameters and used what I have already done, that is, WSL, to determine a few of them. They are: AVG_READING_SPEED, TRASH_COEFFICIENT, EXERCISE_DRAG, HOURS_SPENT_A_DAY. I managed to put a below avarage reading speed, because it is necessary to comprehend a great deal of it; threw in a 30% trash coefficient, that is, 30% of the text is probably irrelevant; 11x exercise drag, which means that 11/12 of my time is going to be towards experimenting instead of actually reading; and hours dedicated a day. I ended up with a little more than I was initially expecting, nothing unmanageable though.",0,0
12/2/2024,Docker Volumes ,Research,7h,12h00,Learning about docker volumes,0,0
12/2/2024,"Docker Bind Mounts, Docker Tmpfs, Docker Storage Drivers",Research,13h30,18h,Studying the different types of volumes that can be created and mounted into a container. ,0,0
12/2/2024,"Docker OverlayFS, Docker Containerd",Research,20h18,21h55,"Getting in touch with how to overlayFS works as well as important innerworking such as the copy up under the hood operation. Right now, I am getting both bored and, at the same time, annoyed by having to manually write these entries in this tables and upload the file every two weeks. Upon finishing set up, I will have to create a UI with a bare minimum CRUD API that will comunicate with this shitty table and the actual indexed data. However, I cannot display it publicly as it contains fucking copyrighted content.",0,0
12/03/2024,Requesting Static IP,Research,12h00,16h,"Hopping onto a long fucking boring call with my ISP to request static IP, the problem is that they called me and I didn't answer. When they call again, I will probably not answer again. This is some serious retarded shit. Now I haave to stay concentrated on this and allocate memory and processing power. ",0,0
12/03/2024,"Main Questão, Formula Questão Integration",Design,16h,18h31,Polishing main question navigation bar.,0,0
12/4/2024,Reporting,Design,9h,9h27,Writing the document that rectifies the frequency agreed upon in the previously document whilst setting up feature analysis for today.,0,0
12/4/2024,Docker Network,Research,10h00,13h00,Studying how the network in docker is configured,0,0
12/4/2024,"Static CGNAT IP, Cloudflare Tunnels, Cloudfare Reliable",Research,14h30,19h30,"Configuring the static IP given from my ISP to work within windows firewall. I don't know how am I going to allow inside WSL and later on inside Docker. However, I think most of it is already solved because of the configuration in wslconfig network mirrored",0,0
12/4/2024,Question Panel,Research,19h30,20h30,Polishing the Quesiton Panel for feature analysis,0,0
12/5/2024,Packet Filtering,Research,7h00,9h00,Learning about how docker applies network rules for filtering incoming traffic for the web and local traffic from within containers. My biggest problem tough is this iptables thing. I don't know how it works and that is annyoing me.,0,0
12/5/2024,Iptables Manual,Research,9h30,11h00,After about 2 hours and reading most of the manual for this linux command I get more or less the ideia of what it does. Its syntax though is kinda tricky but that won't be a problem as I get more used to it when setting up network configuration later on.,0,0
12/5/2024,Network Drivers,Research,11h00,13h30,"Finally I can uderstandd some aspects of what it this section really about. Wthout prior knowledge of this iptables command I wasn't being able to reliably decode the meaning of the commands and was struggling with them. However, this experience in learning network for the first time makes it fun and I look forward to, in the future, study more about it in more dense and on-topic books. I think distributed systems is a super interesting area to dig deep into.",0,0
12/5/2024,"Bridge Network Drivers, Host Network Drivers",Research,14h15,16h00,"Learning about what can be done inside the docker bridge network. However, I am so tired because I have been sleeping late for the past few days and I think I will take the rest of the day off? We'll see.",0,0
12/6/2024,"Docker Net IPVLAN, Docker Net MACVLAN, Docker Net None, Docker Net Overlay",Research,8h00,19h00,Learning about the different types of network that exist and how to manipulate the virtual interfaces and ip addresses that are created for each docker container,0,0
12/7/2024,Docker Networking Tutorials,Research,8h00,13h,"Doing some of the tutorials, all of which could not be entriely completed because they'd require more than one machine of a virtual one and I would not install another ubuntu distro and connect it to docker. This will be done when approapriate.",0,0
12/7/2024,"Docker Start Containers, Resource Constraints ",Research,13h,17h,"Finally, after god kows how many days I finally got in the container part. However, there is a lot to be learned in this area even before start running those containers and really getting to know how the hell do they work. But, as of today, I have spent about 4 days straight reading this manual and even worse, I have got the flu and all my body fucking hurts. That said, I plan to design tomorrows and watch some streams of cellbit's new game before coming back to this.",0,0
12/7/2024,Right Panel,Design,19h,21h,"Well, I have modified the anwsers so they are more focused on the error whenever someone checks the wrong  answer. Also, I have accounted now for exams in which there are more than one correct answer such as those from the south of the country. Still thinking how would the open reponse questions work in such manner. Will the right panel be some sort of ""correctness'' meter? Will students be able to write there? Is this job better suited for a somewhat nerfed version of the editor embed in the body tab? So many questions, so little time to think. I don't know I just got turned off by this project momentarily as I was designing the interface. I literally feel like I want ot puke whenever I see some multiple choice question. I am not only burned out, but somewhat sad with a feeling of so much time wasted. Was it wasted though? Did I not learn a lot an will learn more as time goes by? Did I not learn another valuable lesson from all of this? I think, so. I am starting to see things more positevely and at the same time more decoupled from my inner messed up reality. I desperately need to fucking get out of here. ",0,0
12/8/2024,Right Panel,Design,7h,9h,Taking the day off because I am so fucking wasted ,0,0
12/9/2024,"Mesa>Vestibulares, Navigation Tree",Design,15h,21h30,Starting late because I am tired as hell,0,0
12/10/2024,Docker Run Time Metrics,Research,7h,12h30,Back to docker or so they say.,0,0
12/10/2024,Reporting,Design,6h43,8h31,Polishing right panel to send tomorrow,0,0
12/11/2024,Vestibulares,Design,7h,15h,"Starting to design the vestibulares tab.I didn't like it much because it really looks like youtube in a way, considering it was my starting point. I actually think I will ask for help in order to solve this design assemblance.",0,0
12/13/2024,Vestibulares,Design,7h,18h30,"Holy shit this looks fucking amazing. It is literally what I have always imagined as a platform for me. I am literally Thanos in the ""Fine, I will do it myself""",0,0
12/14/2024,"Vestibulares, Provas",Design,7h,13h,Something wasn't looking quite Right,0,0
12/14/2024,Provas,Design,16h30,8h20h,"Well, now the interface looks way better and the click cost is way low than what I had previously taught. I might add a search bar altogether with that controller to make it easier to find or a view all button somewhere. It's fine for now though. As of now, there are only two problems that are keeping me awake at night: The Question interface that doesn't fit the new look and the overuse of purple. Eventually I will show the UI to other people and they will tell me with my worries stand up.",0,0
12/15/2024,Question Panel,Design ,7h,13h,"I decided to change the question panel in its totality. Now it is way more consistent, however there are some minor adjustements regarding contrast and lline length that seem to not only make the UI overwhelming, but also a little bit clumsy. I will have to fix it later on down the road, because now I have been designing for almost 5 days straight while sick, so I think tomorrow I will study docker for a bit.",0,0
12/15/2024,Question Panel,Design,16h,19h30,"I might have found what was the overall problem with the interface. Looking at medium, their font size is about 20. Giving that I want more or less what medium does very well in reading experience, I adjusted the font size to 20 and it seems to fit my epectations. Another problem is the over use of borders in the progress fillers. Turns out I only needed to fill the whole ball instead of giving it a white border. Matter of fact It resembles the way you fill a gabarito and I liked way more than the previous version. I have also removed those other ugly balls from the faded out ones and it seemed ok. I left the one of the current question though. I tweaked boldness in every aspect of the UI because it was too distracting and the real content, the most important part, was not stading out. I have removed those ugly scissors and I might add them on hover eventually, because they were using too much screen real state and make the UI look rushed.",0,0
12/16/2024,Docker CLI,Research,7h,11h30,Understading the Docker Command Line Tool and how they work together with docker files to build images and do stuff,0,0
12/16/2024,Docker Daemon,Research,13h30,16h40,Learning about what can be done when starting mulitple docker daemon processes as well as figuring out how to get metrics out of it. Seems to not be working properly because we are inside wsl.,0,0
12/16/2024,Metrics Prometheus Docker,Research,17h20,19h48,"I skipped through most off this as it is too deep innerworkings of how the docker deamon is actually implemented. But one thing is holding me back and that is the metric collection seems to not be working properly. I might as well skip it, but my heart is not letting me do it. I guess I will have to come back to it tomorrow. Also, this section is mostly how to troubleshoot the docker daemon when it starts to misbehave, I guess it isn't that important right now so it is somewhat OK to skip most part of it. I take a closer look tomorrow despite not wanting to.",0,0
12/17/2024,Metrics Prometheus Docker,Research,7h,9h,"I can't believe it. I spent I don't know how many hours yesterday trying to debug why the metrics collection wasn't working and I just couldn't figure out. So I took this early morning hours to dig deep into it and it turns out the documentation is kinda wrong. Basically, whenever prometheus was trying to access its metrics from inside the container, it was being able to. However, whenever it tried to access docker's metrics from the host ip address, docker was in fact exposing its metrics on localhost, not in the ip address it was supposed too. This is because the documentation was telling us to do so. That's why the stack overflow questions which suggested sending the metrics through the docker IP directly worked, because when --add-host host.docker.internal:host-gateway added and entity in /etc/hosts file, it was corrrectly mapping to the enpoint docker daemon had created from the daemon.json. ",0,0
12/17/2024,Docker Manage Resources,Research,9h,10h30,"Now that this is solved I can go onto the next one. And I understimate how boring would be to read the full documentation, but now I have to finish this through. I am, however, concerned with elastic's. I will not by no means read that shti top to bottom. I don't really think it is necessary and it will honestly be somewhat a waste of time. But we will see.",0,0
12/17/2024,Docker Logging and Metrics,Research,10h30,12h30,"Holy shit, if I hear the word ""driver"" once more in this documentation I swear I am going to kill myself.",0,0
12/17/2024,Mesa Vestibulares,Design,16h,19h,"Well, I had an amazing idea of how to display the drawers in the UI so I ditched the documentation for today and tried it out. And I am proud to say that it actually worded and in fact it was better than I had initially expected. Things look so muhc clearer now without those messy buttons and that overlay is just fire.",0,0
12/18/2024,Reporting,Research,7h45,8h36,Reporting stuff and writing everything I was supposed to write yesterday.,0,0
12/18/2024,Mesa Vestibulares,Design,8h36,16h00,"I literally spent half a fucking day tweaking this interface and now it really looks awesome. I got some help I wasn't expecting it would be so productive. She pointed out some flaws and misunderstading that were so obivous but I was likewise so oblivious to them that I felt embarassed. Now, everything is somewhat working, time to report.",0,0
12/18/2024,Reporting,Research,16h00,17h20,"Reported everything, time for a break, eat something an get back to learning docker. Or I will do this tomorrow, because today was a busy day. I will probably come back later to the drawers that seem to be waiting for me to start them. Also, I think I will finally design the question body stuff idk.",0,0
12/19/2024,Docker Log Driver,Research,5h,10h,I hate drivers.,0,0
12/19/2024,"Mesa Vestibulares, Mesa Questão: Corpo, Resposta",Design,10h,18h,"I want to fucking kill myself. I was thinking about why does this interface doesn't look pleasing to the eye and I might have found my answer. After extensively researching dashboards, I noticed the following pattern: Every single one of them has metrics which stay within the same container everytime. I literally spent an hour trying to find one that didn't and shot myself in the foot. Therefore, one of the reasons this interface might not look like great is because I have to flicker my eyes through the screen to see the metrics I wanted. As a simple test, I moved all the metrics to one side of the screen and both shockingly and suddendly it looked 10% better. Still, there is something that is missing. I think one of the reasons might be also because the header in the middle of the screen is taking up so much real state that could be used more efficiently. I will have to completely redesign that interface. Thank god I have something to build upon.",0,0
12/20/2024,Docker,Design,9h,17h,"I am almost finished with the most part of the docker engine. I cannot believe I have made it through. I think I will actually skip swarm mode for now, because it is not really necessary as I will have only a single host. I will for now read only the overview and mark it as read later.",0,0
12/21/2024,Docker,Research,7h,12h,"Today is my birthday and I can finally by a .com.br domain. I am so happy. I will probably make sure that everything gets hosted properly in a few weeks. For now, everything is going to be pretty standard. ",0,0
12/21/2024,Private and Public Keys,Research,18h,20h,"Even though I love information security, this has my head going nuts",0,0
12/24/2024,Docker Build,Research,5h,11h,"Well, I decided to skip swarm mode as it relates to something I will literally not use for at least more 10 months or so. There is not really a point in learning something which is not really make any difference in the prototype application. ",0,0
12/24/2024,Docker Build,Research,13h,17h,"I have non ironically made aa hello world in go, without even noticing takes to the power of docker. ",0,0
12/24/2024,HTTP,Research,17h ,19h,"I have decided to start reading that HTTP book I downloaded to learn along with python but never got the opportunity to finish it properly. Now that I have more time, I can finally learn more and stop blaming myself for being so dumb with cros policy. That is, if that book actually covers it because it is pretty old. Not older than the that other one from that website I don't remeber the name though. It is written in an obscure language from 38 years ago, but as the author said it is pretty simple. ",0,0
12/25/2024,Reporting,Research,7h,7h21,Reporting stuff and writing everything I was supposed to write yesterday.,0,0
12/26/2024,"Nginx, Dockerfile Pratice",Research,7h,21h30,"God, It had been a long time since I hadn't had this much fun doing stuff. This feeling came along because everything felt so new and I literally didn't know what I was doing for the first 3 hours or so. But, the feeling you get connecting the dots and not knowing if that is going to work or not is just incredible. Matter of fact, every time I ran build my heart started racing.",0,0
12/27/2024,HTTP,Research,7h,11h30,Started reading the basics of the http protocol as I don't want to ever deal again with cros csr policy,0,0
12/27/2024,HTTP,Research,16h,20h,"At last, finished the first two chapters of this book. Onto to the next!",0,0
12/28/2024,"Vim, Vim Themes",Research,6h,7h30,"I don't think I am prepared to make a full blown switch, but as I get more accostumed with it, eventually I will probably swich to vim. That is because if you look, the whole stack I am working with is supported natively on linux. And now, as I jump start into container, I will not have the luxury of vs code installed by default on every single one of them, as I will have if I get better at doing stuff with vim. As I am not really looking to jump into game development for the time being, sticking to windows and vs code will probably be the wrong call in the long run. ",0,0
12/28/2024,Ubuntu,Research,7h30,15h24,Changing my distro because wsl2 was getting in my way to say the last,0,0
12/28/2024,Minecraft,Code,17h,22h,"I am probably gonna be sick again, because my sister has the flu. Today my head hurts so much. Nonethless, I had my hello world in minecraft servers and I even installed many plugins that allow for bedrock and java to interoperate. The donwisde though is that it consumes a shitload of ram, more or less frustating my expectations of hosting it alongside the main website.",0,0
12/29/2024,Ubuntu,Research,7h,11h,"Yeah, I have a headache that is driving me nuts, it is minor though.  Nonetheless, I couldn't do muhc today so I decided I was going to finish setting up my new distro. To be honest, I am a really bit worried, because a lot of things are not working as fluid as in windows. You cannot make the cake and eat it too.",0,0
12/29/2024,Ubuntu,Research,15h,17h," I finally finished the OS transition. This required some boring and exhausting tweaking, because not every driver is working as it is supposed to. Something is not quite right with my wireless adapter, because despite my internet being generally fast, it keeps going down. However, I wonder if it isn't a problem with the ISP itself. ",0,0
12/30/2024,Docker Building ,Research,8h,9h,"I am still a little bit wasted and I don't want to do anything today. I am actually procastinating, but I am for sure this is because I was supposed to be sick. Thank god my immune system is still up and running.",0,0
12/30/2024,Docker Building ,Research ,16h ,19h,"So I have finished the build overview of the docker documentation. There is so much I can do now that ttwo months ago I would think it was impossible and would cause mroe headaches than benefits such as polute my filesystem with useless packages. I am truly amazed by the possibilities of this technology and grateful I decided to start by it. Just the other day I made a hello world in go without even noticing. I think tomorrow I will finish the build drivers and go back to nginx before docker bake, as it seems to be complex. ",0,0
12/31/2024,Docker Builders,Research,6h30,8h30,"I was supposed to study nginx today, but as the tabs were already opened, I continued for a bit. ",0,0
12/31/2024,Nginx,Research,8h30,17h,"Spent the rest of the day learning about nginx though. NJS seems promise, there were a lot of use cases and it got me a little hooked. Though I wonder if doing the same thing with react wouldn't be better, but latency wise I don't think so ( authenticating in the proxy layers seems to be better than to call other library to do so). Now I got to fucking go. ",0,0`

    // const asset = await fetch('./report.txt');
    // const text = await asset.text();
    const rows = text.split('\n');
	
    const headers = rows.shift().trim().split(',')

    const reversed = rows.reverse();
    const entries = new Map();

    for (let row of reversed) { 

        const regExp = /,(?=(?:[^"]*"[^"]*")*[^"]*$)/
        const entry = row.trim().split(regExp).reduce((acc, value, index) => (acc[headers[index]] = value, acc), {});
	
		const date = new Date(entry.day)
		const ds = date.toDateString();

		if (!entries.has(ds))
			entries.set(ds, { things: {}, intervals: [] });

		const day = entries.get(ds)
		
		const things = entry.main.replaceAll(`"`, '').split(',').map(thing => thing.trim());
		const duration = handleDuration(entry.day, entry.start, entry.end);

		const avg = duration.long / things.length;

		for (let thing of things) {

			thing = thing.toLowerCase();

			if (!day.things[thing])
				day.things[thing] = 0;

			day.things[thing] += avg
		}

		day.intervals.push({ things, duration, comment: entry.comment.trim().replaceAll('"', ''), domain: entry.domain.toLowerCase() })
    };

	return { entries: JSON.stringify(Array.from(entries.entries())) };
}

function handleDuration(date, start, end) {

	start = start.toLowerCase().replace('min').split('h').map(e => +e);
	end = end.toLowerCase().replace('min').split('h').map(e => +e);

	let startTime = new Date(date);

	startTime.setHours(start[0])
	startTime.setMinutes(start[1])

	let endTime = new Date(date);

	endTime.setHours(end[0])
	endTime.setMinutes(end[1])

	return {
		start: startTime.getTime(),
		end: endTime.getTime(), 
		long: endTime.getTime() - startTime.getTime(),
	}
};

export const prerender = true